# Slightly tuned presets for final quality targets

from typing import Dict

PRESETS = {
    "low_latency": {
        "resolution": "720p",
        "fps": 30,
        "use_enhancer": False,
        "poisson_blend": False,
        "fp16": True,
        "advanced_controls": {
            "identity": 65,
            "forehead": 60,
            "eyebrows": 65,
            "eyes": 75,
            "upper_eyelids": 75,
            "lower_eyelids": 75,
            "nose": 68,
            "cheeks": 60,
            "cheekbones": 60,
            "mouth": 45,
            "jaw": 60,
            "chin": 60,
            "face_shape": 60,
            "skin_texture": 50,
            "color_matching": 60,
            "hairline": 50,
            "expression_preservation": 85,
            "eye_blink_preservation": 90,
            "mouth_movement_preservation": 95,
            "teeth_preservation": 95,
            "mask_size": 98,
            "mask_feathering": 10,
            "blending_strength": 0.75,
            "color_correction_strength": 0.7,
            "enhancer_strength": 0.25,
            "temporal_smoothing": 0.75,
        },
    },
    "balanced": {
        "resolution": "1080p",
        "fps": 30,
        "use_enhancer": True,
        "poisson_blend": True,
        "fp16": True,
        "advanced_controls": {
            "identity": 82,
            "forehead": 80,
            "eyebrows": 82,
            "eyes": 88,
            "upper_eyelids": 85,
            "lower_eyelids": 85,
            "nose": 85,
            "cheeks": 80,
            "cheekbones": 80,
            "mouth": 65,
            "jaw": 80,
            "chin": 80,
            "face_shape": 80,
            "skin_texture": 80,
            "color_matching": 85,
            "hairline": 72,
            "expression_preservation": 72,
            "eye_blink_preservation": 82,
            "mouth_movement_preservation": 78,
            "teeth_preservation": 82,
            "mask_size": 100,
            "mask_feathering": 16,
            "blending_strength": 0.9,
            "color_correction_strength": 0.9,
            "enhancer_strength": 0.6,
            "temporal_smoothing": 0.82,
        },
    },
    "high_quality": {
        "resolution": "1080p",
        "fps": 60,
        "use_enhancer": True,
        "poisson_blend": True,
        "fp16": True,
        "advanced_controls": {
            "identity": 92,
            "forehead": 90,
            "eyebrows": 92,
            "eyes": 95,
            "upper_eyelids": 92,
            "lower_eyelids": 92,
            "nose": 92,
            "cheeks": 90,
            "cheekbones": 90,
            "mouth": 78,
            "jaw": 90,
            "chin": 90,
            "face_shape": 90,
            "skin_texture": 92,
            "color_matching": 93,
            "hairline": 86,
            "expression_preservation": 62,
            "eye_blink_preservation": 78,
            "mouth_movement_preservation": 72,
            "teeth_preservation": 82,
            "mask_size": 105,
            "mask_feathering": 18,
            "blending_strength": 0.95,
            "color_correction_strength": 0.95,
            "enhancer_strength": 0.85,
            "temporal_smoothing": 0.9,
        },
    },
    "maximum": {
        "resolution": "4k",
        "fps": 60,
        "use_enhancer": True,
        "poisson_blend": True,
        "fp16": True,
        "advanced_controls": {
            "identity": 100,
            "forehead": 100,
            "eyebrows": 100,
            "eyes": 100,
            "upper_eyelids": 100,
            "lower_eyelids": 100,
            "nose": 100,
            "cheeks": 100,
            "cheekbones": 100,
            "mouth": 95,
            "jaw": 100,
            "chin": 100,
            "face_shape": 100,
            "skin_texture": 100,
            "color_matching": 100,
            "hairline": 100,
            "expression_preservation": 40,
            "eye_blink_preservation": 60,
            "mouth_movement_preservation": 50,
            "teeth_preservation": 60,
            "mask_size": 110,
            "mask_feathering": 22,
            "blending_strength": 1.0,
            "color_correction_strength": 1.0,
            "enhancer_strength": 1.0,
            "temporal_smoothing": 0.95,
        },
    },
}
